MACOSX_DEPLOYMENT_TARGET:   # [osx]
  - '10.9'                  # [osx]
MACOSX_SDK_VERSION:         # [osx]
  - '10.10'                 # [osx]
c_compiler_version:         # [osx]
  - '11.0.0'                # [osx]
cxx_compiler_version:       # [osx]
  - '11.0.0'                # [osx]
